### ISSUE TITLE
Result empty

### ISSUE THREAD

**Issue by LiloBzH** [moisseev/received#1]
Hi

Its better here

Exemple of headers :

==============================================================================
Return-Path: <noreply.orange@gmail.com>
Received: from mywebsite.com
	by localhost (Dovecot) with LMTP id GXBxEZkPiFVlPQAA0J78UA
	; Mon, 22 Jun 2015 15:37:29 +0200
Received: by mywebsite.com (Postfix, from userid 121)
	id 455313C2B7A; Mon, 22 Jun 2015 15:37:29 +0200 (CEST)
X-Spam-Checker-Version: SpamAssassin 3.4.0 (2014-02-07) on website
X-Spam-Level: 
X-Spam-Status: No, score=-0.7 required=3.0 tests=FREEMAIL_FROM,HTML_MESSAGE,
	RCVD_IN_DNSWL_LOW,RCVD_IN_MSPIKE_H4,RCVD_IN_MSPIKE_WL,URIBL_BLOCKED
	autolearn=ham autolearn_force=no version=3.4.0
Received: from mh.cvf.fr (mh4.cvf.fr [94.124.129.50])
	by mywebsite.com (Postfix) with ESMTP id BA0A03C2B78
	for <moi@mywebsite.com>; Mon, 22 Jun 2015 15:37:26 +0200 (CEST)
Received: from [10.94.34.141] (helo=ogp-webbo01c.ogp94.cvf)
	by mh.cvf.fr with esmtp 
	for <moi@mywebsite.com>id 1Z71uf-0000U3-Sz; Mon, 22 Jun 2015 15:37:26 +0200
Received: from localhost (localhost [127.0.0.1])
	by ogp-webbo01c.ogp94.cvf (Postfix) with SMTP id 8B7741D865D
	for <moi@mywebsite.com>; Mon, 22 Jun 2015 15:35:35 +0200 (CEST)
Errors-To: <noreply.orange@gmail.com>
Reply-To: Orange / Service de presse <noreply@orange.com>
x-cjwnl-version: 2.0.0.201308160914
x-cjwnl-receiver: moi@mywebsite.com
x-cjwnl-user: 988458152cfc052f76ad4b8d0e43553f
x-cjwnl-senditem: dfc34313fd39d2fce931bfff805de9f1
x-cjwnl-subscription: ed2610340690abfd3051d29b423568da
From: Orange / Service de presse <noreply@orange.com>
To: Moi <moi@mywebsite.com>
Subject: =?utf-8?Q?NeoRetro,=20retour=20ve?==?utf-8?Q?rs=20le=20f?=
 =?utf-8?Q?utur=20du=20t=C3=A9l=C3=A9phone=20f?==?utf-8?Q?ixe?=
MIME-Version: 1.0
User-Agent: Apache Zeta Components
Date: Mon, 22 Jun 2015 15:35:35 +0200
Message-Id: <2015062215152235.31762.4055@orange.com>
Content-Type: multipart/alternative; boundary="2015062215152235:31762:4055"

====================================================

regular expression is : (.*) (default for now because i'm not a specialist of regular expression !)

But no result :

![rec](https://cloud.githubusercontent.com/assets/4649466/8305189/eb5baa52-19ac-11e5-9137-c48538c26b26.png)

i want to display sender informations . In this example : 
Received: from mh.cvf.fr (mh4.cvf.fr [94.124.129.50])

Thanks

PS : Sorry for my english ^^ (and for your help)

**Comment by moisseev** [comment]
I am sorry for my English too.

I can't reproduce the issue. I have created a message with the headers you posted, imported it into Thunderbird and it works. But that test was not "clean" since I had to do some formatting. Could you save the message into eml file an upload somewhere?

If you have the issue with only one message then It is probably some problem with internal Thunderbird indexes or so. In this case try to save the message into a eml file and drag-and-drop it back to the Thunderbird. This add-on will not work if you just open eml file but only for messages in Thunderbird folders.

Regarding regular expression. `(.*)` is ok for testing, you will get all Received headers displayed at once. To display `Received: from mh.cvf.fr (mh4.cvf.fr [94.124.129.50])` you can start with `.+from (.+?) by mywebsite.com \(Postfix\) with ESMTP ` and then adopt it to specific cases.

**Comment by LiloBzH** [comment]
un exemple : 
http://www.lilobzh.com/test.eml

**Comment by moisseev** [comment]
It works.
![test](https://cloud.githubusercontent.com/assets/2275981/8310713/6f57d380-19da-11e5-81da-59c89d43d44b.png)
It might be conflict with some other add-on. Could you temporarily disable other add-ons?

BTW what OS and Thunderbird version are you using?

**Comment by LiloBzH** [comment]
whaou ... no add on
Win 7 64 - TB 38.0.1

**Comment by moisseev** [comment]
Finally I have reproduced the issue on Thunderbird 17.0.5

**Comment by LiloBzH** [comment]
tb 17 . old version ^^

**Comment by moisseev** [comment]
It doesn't matter, but now I can investigate the problem.

**Comment by LiloBzH** [comment]
i will test with clean TB too.

**Comment by LiloBzH** [comment]
It doesn't work with clean TB.
Line is empy

**Comment by moisseev** [comment]
I am very sorry, I missed a thing in the add-on. I will fix it.

Temporary solution: add `Received` to the `mailnews.customHeaders` setting in the config editor.

This will take effect for newly received messages as soon as you restart Thunderbird. If you want to fix the “Received“ column values for messages that already in a folder, then you must open the folder's properties dialog (right-click or ctrl-click on it and select “Properties...”) and click the “Repair Folder” button. Note that this will, unfortunately, reset your visible columns and their widths.

**Comment by LiloBzH** [comment]
yess !!! Good job.

It's ok for me. Thank you :)
