### ISSUE TITLE
What regex to see the part after the "by mx\.example\.com" ?!

### ISSUE THREAD

**Issue by versus167** [moisseev/received#2]
Hello I try to find a regex for this extension. I want to see the complete receive-string where the mail reaches my server. 

My attempt with: "Received: from(.+?)by mx\.example\.com(.+?);" doesn't work :/ 

Any idea?

Thanks in advance!

**Comment by moisseev** [comment]
I am not sure what exactly you want to see.

Complete `Received` header:
```regex
(.*by mx\.example\.com.*)
```
Trailing part of the header (after the "by mx.example.com"):
```regex
by mx\.example\.com(.*)
```
If it is not what you are looking for, please post an example of the header and specify the part you want to see.

**Comment by versus167** [comment]
Ah, thank you, 'The complete received header' was my goal!
