### ISSUE TITLE
'received' is not compatible with thunderbird 78

### ISSUE THREAD

**Issue by versus167** [moisseev/received#4]
Are there any plans to upgrade "received"?!

**Comment by moisseev** [comment]
Not yet.

`receiveds` is a XUL extension and `Thunderbird 78` doesn't support XUL. Support for "legacy" add-ons was removed in Thunderbird 74beta. The only way is rewriting the add-on using modern `MailExtensions` API, but currently I have no plans for this.

**Comment by versus167** [comment]
Okay, thanks for the info. I found this extension really useful to see the real source of a mail.

**Comment by versus167** [comment]
And now it works with Thunderbird 78! Thank you!
