### ISSUE TITLE
Not sure what to look for?

### ISSUE THREAD

**Issue by zell-mbc** [moisseev/received#6]
I just installed this AddOn to see if it is of help to me. But I am not sure what to expect after installing it? The Thunderbird UI seems to be unchanged. Should there be a new view or menu item? Right now I am not sure if I simply haven't found the new information in the UI or if maybe the AddOn doesn't work for some reason.

I am running Thunderbird v. 100.0b4

**Comment by moisseev** [comment]
It should add [Received](https://addons.thunderbird.net/user-media/previews/full/140/140302.png) header to the pane.

I don't test the add-on on Thunderbird beta versions. In case if it is broken, Thunderbird should throw an error which can be seen on the developer console.

**Comment by Nothing4You** [comment]
I'm seeing the same behavior when trying 101.0b1, also affects rspamd-spamness:

<img width="1910" alt="image" src="https://user-images.githubusercontent.com/3694534/166686862-586e6c7f-c2e5-47ed-9c08-985661bb3faf.png">

This is on Received 2.3.1.

<img width="705" alt="image" src="https://user-images.githubusercontent.com/3694534/166687019-b5d9f0e7-b821-41f1-9c9a-75a80cb12ff5.png">

<img width="331" alt="image" src="https://user-images.githubusercontent.com/3694534/166687051-e123ed0d-1646-40eb-a537-3ac045d2b53d.png">

<img width="640" alt="image" src="https://user-images.githubusercontent.com/3694534/166687088-6a5dd6ed-5fb6-4752-8bb0-d3ec52c48997.png">

**Comment by Nothing4You** [comment]
When disabling and re-enabling the extension it logs the following error:
```
Error: Could not find the expandedHeaders2 element
```

<img width="621" alt="image" src="https://user-images.githubusercontent.com/3694534/166688060-d3c1210c-9c70-4310-ab78-e2e8867578db.png">

**Comment by Nothing4You** [comment]
structure seems to have changed a bit from 91.9.0:
<img width="603" alt="image" src="https://user-images.githubusercontent.com/3694534/166688548-4b96261a-6419-4e55-bd24-f7646d3653e7.png">
to
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/3694534/166688692-340761d4-4c17-42eb-8dae-d57bc6b511a4.png">
